# Generated by Django 5.2.1 on 2025-05-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('Suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('Role', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Account_Status', models.CharField(default='inactive', max_length=20)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('riceID', models.AutoField(primary_key=True, serialize=False)),
                ('rice_type', models.CharField(max_length=100, unique=True)),
                ('price_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_in', models.PositiveIntegerField(default=0)),
                ('stock_out', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Rice',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('Role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('cashier', 'Cashier'), ('customer', 'Customer')], default='customer', max_length=50)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Acc_Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('Customer_Mobile_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('House_Unit_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Building_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Street_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('City_Municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('Province', models.CharField(blank=True, max_length=100, null=True)),
                ('ZIP_Code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'webapp_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.employee')),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=50)),
                ('rice_per_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilo_of_rice', models.IntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_method', models.CharField(default='Delivery', max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('approval_status', models.CharField(default='Pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.users')),
            ],
            options={
                'verbose_name': 'webapp_supplier',
                'verbose_name_plural': 'webapp_supplier',
                'db_table': 'webapp_supplier',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('credit_card', 'Credit Card')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=20)),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_mobile_number', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='webapp.employee')),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_handled', to='webapp.employee')),
                ('rice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.rice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.users')),
            ],
            options={
                'db_table': 'webapp_customerorder',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('old_values', models.JSONField(null=True)),
                ('new_values', models.JSONField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.users')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
