# Generated by Django 5.2 on 2025-05-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_customerorder_is_active_customerorder_order_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_unit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_name',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='Barangay',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Building_Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='City_Municipality',
        ),
        migrations.RemoveField(
            model_name='users',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='House_Unit_Number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Middle_Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Street_Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Suffix',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ZIP_Code',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='webapp.useraddress'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='webapp.username'),
        ),
    ]
