# Generated by Django 5.2.1 on 2025-05-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_customerorder_supplier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='users',
            name='unique_username_email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Acc_Status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_email_verified',
        ),
    ]
