# Generated by Django 5.2.1 on 2025-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_users_unique_username_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rice',
            name='packaging',
            field=models.CharField(default='50kg', max_length=50),
        ),
    ]
