# Generated by Django 5.2.1 on 2025-05-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rice_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='price_per_sack',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='stock_in',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='stock_out',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockID', models.AutoField(primary_key=True, serialize=False)),
                ('packaging', models.CharField(default='50kg', max_length=50)),
                ('price_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_in', models.PositiveIntegerField(default=0)),
                ('stock_out', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rice_type', models.ForeignKey(db_column='riceID', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='webapp.rice')),
            ],
            options={
                'db_table': 'Stock',
                'unique_together': {('rice_type', 'packaging')},
            },
        ),
    ]
