# Generated by Django 5.2 on 2025-05-28 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_rice_created_at_remove_rice_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='supplier',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='Approved', max_length=20),
        ),
    ]
