from django.urls import path
from . import views

urlpatterns = [
    path('undo_update/<int:log_id>/', views.undo_update, name='undo_update'),
    path('ajax/get-customer-details/', views.get_customer_details, name='get_customer_details'),
    path("", views.home, name="home"),
    path('login/', views.home, name='login'),   
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("new-sale/", views.new_sale_view, name="new_sale"),
    path("view-sales-history/", views.view_sales_history, name="view_sales_history"),
    path("view-sales-report/", views.view_sales_report, name="view_sales_report"),
    path("inventory-turnover/", views.inventory_turnover, name="inventory_turnover"),
    path('adduser/', views.adduser, name='add_user'),
    path("edituser/", views.edituser, name="edituser"),
    path("supplier/", views.supplier, name="supplier"),
    path("addstock/", views.addstock, name="addstock"),
    path("viewstocklevel/", views.viewstocklevel, name="viewstocklevel"),
    path('logout/', views.logout_view, name='logout'),
    path('edituser/<int:EmployeeID>/', views.edituser, name='edituser'),
    path('deleteuser/<int:EmployeeID>/', views.delete_user, name='delete_user'),
    path('profile/', views.profile, name='profile'),
    path('deletestock/<int:rice_id>/', views.deletestock, name='deletestock'),
    path('customer-orders/', views.customer_orders_view, name='orders'),
    path('approve_order/<int:order_id>/', views.approve_order, name='approve_order'),
    path('decline_order/<int:order_id>/', views.decline_order, name='decline_order'),
    path('process_order/', views.process_order, name='process_order'),
    path('edit-order/<int:order_id>/', views.edit_order, name='edit_order'),
    path('delete-order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('add_rice/', views.add_rice, name='add_rice'),
    path('updatestock/<int:riceID>/', views.updatestock, name='update_stock'),
    path('logs/', views.user_logs, name='logs'),
    path('customer-orders/', views.customer_orders_view, name='customer_orders'),
    path('sales-report/', views.view_sales_report, name='view_sales_report'),
    path('inventory_turnover/', views.inventory_turnover_report, name='inventory_turnover'),
    path('sales-history/', views.view_sales_his, name='view_sales_history'),
    path('process_supplier/', views.process_supplier, name='process_supplier'),
    path('restore_user/<int:employee_id>/', views.restore_user, name='restore_user'),
    path('delete_supplier/<int:supplier_id>/', views.delete_supplier, name='delete_supplier'),
    path('update_supplier_status/<int:supplier_id>/', views.update_supplier_status, name='update_supplier_status'),
    path('backup/', views.backup_database, name='backup_database'),
    path('restore/', views.restore_database, name='restore_database'),
    path('signup/', views.Process_signup, name='signup'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('userprofile/', views.userprofile, name='userprofile'),
    path('my-account/', views.user_account_view, name='user_account'),
    path('add-announcement/', views.add_announcement, name='add_announcement'),
    path('announcement/edit/<int:announcement_id>/', views.edit_announcement, name='edit_announcement'),
    path('announcement/delete/<int:announcement_id>/', views.delete_announcement, name='delete_announcement'),
    path('permanent-delete-user/<int:employee_id>/', views.permanent_delete_user, name='permanent_delete_user'),
    path('order/', views.place_order, name='place_order'),
    path('delivery-management/', views.delivery_management, name='delivery-management'),
    path('update-delivery-status/', views.update_delivery_status, name='update_delivery_status'),
    path('orders/reset-status/<int:order_id>/', views.reset_delivery_status, name='reset_order_status'),   
    path('supplier-order/', views.supplier_order, name='supplier_order'),

]
    

